### ISSUE TITLE
VSCode-linux64.zip not found for 0.10.8 or 0.10.10

### ISSUE THREAD

**Issue by pflannery** [Microsoft/vscode-extension-vscode#18]
when trying to set `process.env.CODE_VERSION`  to `0.10.8 or 0.10.10` VSCode-linux64.zip is not found

example link issue: https://az764295.vo.msecnd.net/public/0.10.10/VSCode-linux64.zip

**Comment by SamVerschueren** [comment]
Same happens for Mac OSX, it seems that the latest version published to public is `0.10.5`. I use the following `test` script.

```
CODE_DOWNLOAD_URL=https://go.microsoft.com/fwlink/?LinkID=620882 node ./node_modules/vscode/bin/test
```

It's the direct link to the latest stable version for Mac OSX. Find the Linux version on the VS Code website and you should be good to go.

**Comment by bpasero** [comment]
We did some changes with the download URL from our CDNs and I pushed a new version of the vscode module that hopefully fixes this issue.

**Comment by SamVerschueren** [comment]
Works perfectly! 

// Offtopic
Tests are failing on Linux however for the [`EditorConfig`](https://travis-ci.org/editorconfig/editorconfig-vscode/jobs/114476876) extension, not sure if this has something to do with it. Probably not.

**Comment by bpasero** [comment]
@SamVerschueren you can always run them locally from the workspace: node ./node_modules/vscode/bin/test

**Comment by pflannery** [comment]
I still cant download 0.10.10 for linux when using the commit https://az764295.vo.msecnd.net/stable/45d69357c9eb068dd8e624f5b0fe461cd2078d88/VSCode-linux64.zip

But when using the direct 0.10.10 dowload url it works. https://go.microsoft.com/fwlink/?LinkID=620884

Now I hit a new problem where the `linuxExecutable` is set to use `Code` instead of `code` and wont launch on linux. https://github.com/Microsoft/vscode-extension-vscode/blob/master/bin/test#L43

**Comment by Tyriar** [comment]
@pflannery created https://github.com/Microsoft/vscode-extension-vscode/issues/19, ping that issue if it needs any more details.

**Comment by bpasero** [comment]
@pflannery the correct link for Linux 64 0.10.10 is: https://az764295.vo.msecnd.net/stable/5b5f4db87c10345b9d5c8d0bed745bcad4533135/VSCode-linux-x64-stable.zip

**Comment by craigb** [comment]
Hey guys, does this package support development in windows? Looking at the test script, I only see references to linux or darwin binaries.

**Comment by bpasero** [comment]
The integration tests are currently not supported on Windows. You can of course write your own mocha tests that run headless.
